version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker build -t cpac:${CIRCLE_BRANCH//\//_} .
  heatmaps:
    machine: true
    steps:
      - run:
          name: ≟
          command: pwd && ls && cd $HOME && ls && cd project && ls
          # python $HOME/project/dev/circleci_data/scripts/compare.py
  test:
    machine: true
    steps:
      - run:
          name: Run C-PAC
          command: docker run -i --rm -v $HOME:/output -v /tmp:/tmp cpac:${CIRCLE_BRANCH//\//_} s3://fcp-indi/data/Projects/RocklandSample/RawDataBIDS /output participant --participant_label A00028185 --pipeline_file /cpac_resources/pipe-test_ci.yml
          no_output_timeout: 3h

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - heatmaps:
          requires:
            - build
          filters:
            branches:
              only: feature/auto-heatmaps
      - test:
          requires:
            - build
          filters:
            branches:
              ignore:
                - feature/auto-heatmaps
                - upgrade/python3
